Plotting/MakeResonancePlots.py
=> update plotting script

Analysis/TreeFilter/FilterPhotonOlap15/scripts/scheduler.py, Analysis/TreeFilter/FilterPhotonOlap15/src/RunAnalysis.cxx, Analysis/TreeFilter/FilterResonance/scripts/Conf.py, Analysis/TreeFilter/FilterResonance/scripts/scheduler.py, Analysis/TreeFilter/FilterResonance/src/RunAnalysis.cxx, Analysis/TreeFilter/RecoPhoton15/src/RunAnalysis.cxx, Plotting/MakeResWJetsBkg.py, Plotting/MakeResonancePlots.py, Plotting/Makefile, Plotting/Modules/Resonance.py, Plotting/interactiveStackTree.py, Plotting/selection_defs.py
=> Merge code

Plotting/MakeFits.py, Plotting/MakeWorkspaces.py, Plotting/Makefile
Remove UUID nonsense from signal models.  Signal workspaces should be regnerated
=> Fix signal workspaces

Plotting/FitManager.py, Plotting/MakeSignalWS.py, Plotting/MakeWJetsWS.py
MakeWJetsWS is now working
Some updates to FitManager were needed to accommodate those changes
Some minor changes to MakeSignalWS were required as a result
=> Get MakeWJets working

Analysis/TreeFilter/Core/python/core.py, Analysis/TreeFilter/FilterOverlap/scripts/scheduler.py, Analysis/TreeFilter/RecoResonance/include/RunAnalysis.h, Analysis/TreeFilter/RecoResonance/scripts/Conf.py, Analysis/TreeFilter/RecoResonance/scripts/scheduler.py, Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx, README.md
Reverts albertobelloni/WG_Analysis#41
=> add metfilter. Update a little bit on the object selection

Analysis/Util/scripts/check_datasets_das.py, Plotting/SampleManager.py
option to veto failed jobs in check_dataset_das.py
Sample object representation, improved options for ratio plots, method to modify stack order
=> SampleManager.py check_dataset_das.py update

Analysis/TreeFilter/Core/python/core.py, Analysis/TreeFilter/RecoResonance/scripts/Conf.py, Analysis/Util/python/check_dataset_completion.py
1. add the condor log file for debugging (can be disabled if need to lower the size.) 
2. Update the make_no_filt to sync with the lepton pt cuts in make_final_xxg. This is for acceptance/efficiency calculations. 
3. skip the failed jobs from crab when splitting jobs and counting nevents.
=> Legacy2016

Plotting/MakeFitsTest.py, Plotting/MakeMCBkgWS.py, Plotting/MakeSignalWS.py, Plotting/Makefile, Plotting/SampleInfo.py, README.md
a few updates including the missing files and code cleaning. README is updated as well. It should work now
=> to get the limits working

Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx
=> Fix for Rochester corrections

Analysis/TreeFilter/ApplyScaleFactors/include/RunAnalysis.h, Analysis/TreeFilter/ApplyScaleFactors/scripts/Conf2016.py, Analysis/TreeFilter/ApplyScaleFactors/scripts/Conf2017.py, Analysis/TreeFilter/ApplyScaleFactors/scripts/Conf2018.py, Analysis/TreeFilter/ApplyScaleFactors/src/RunAnalysis.cxx
(plot for 2016 data/MC, blue=nominal, green=up, red=down)
Very close to 1, so they are probably negligible. But it cannot hurt to have them, just in case somebody asks...
=> Trigger scale factors for dimuon events

Analysis/TreeFilter/ApplyScaleFactors/src/RunAnalysis.cxx, Analysis/TreeFilter/Core/python/core.py, Plotting/MakeMoneyPlot.py, Plotting/Modules/Resonance2016.py, Plotting/Modules/Resonance2017.py, Plotting/SampleManager.py, Plotting/cross_sections/photon16.py, Plotting/cross_sections/photon17.py, Plotting/interactiveStackTree.py
Sample Manager:
1. ymax calculation bug fix
2. draw shaded errors in Draw()
interactiveStackTree:
batch option when X11 is unavailable
core.py
total events to run if num of events is less than specified value
temporariy plotting Z+jets without overlap removal
=> add tW and bug fixes

Plotting/FitManager.py, Plotting/MakeMCBkgWS.py
first order expow: ```[0]*(TMath::Power( x / 13000., [1] ) * TMath::Exp([2]*x/13000.))```
=> Update expow definition

.gitignore, Analysis/TreeFilter/ApplyScaleFactors/scripts/scheduler.py, Analysis/TreeFilter/FilterOverlap/scripts/scheduler.py, Analysis/TreeFilter/Makefile.mk, Analysis/TreeFilter/Makefile_RC.mk, Plotting/DrawConfig.py, Plotting/MakePlots.py, Plotting/SampleManager.py, Plotting/cross_sections/photon16.py, Plotting/cross_sections/photon17.py, Plotting/cross_sections/photon18.py, Plotting/selection_defs.py
* Different fixes (see commits)
* Can run full Z control region plots with simple command now, for example:  `python MakePlots.py --baseDir /data/users/mseidel/Resonances2016 --tag 2019_11_13/WithSF --makeZCR`
=> Analysis and plotting fixes

Plotting/cross_sections/photon16.py, Plotting/cross_sections/photon17.py, Plotting/cross_sections/photon18.py
[theoretical production cross-sections](http://hepcms-hn.umd.edu/~kakw/sigmaBR_FoldedSUSY_Wgamma.txt) of f-squark model from Rodolfo Capdevilla
There are a few place we don't have numbers which I substitue with a rough estimate
=> Updated signal cross-section

Analysis/TreeFilter/RecoResonance/include/RunAnalysis.h, Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx, Plotting/cross_sections/photon16.py, Plotting/cross_sections/photon17.py, Plotting/cross_sections/photon18.py
=> Update signal cross-section extrapolation

Analysis/TreeFilter/RecoResonance/scripts/Conf2016.py, Analysis/TreeFilter/RecoResonance/scripts/Conf2017.py, Analysis/TreeFilter/RecoResonance/scripts/Conf2018.py, Plotting/Modules/Resonance2016.py, Plotting/Modules/Resonance2016_efake.py, Plotting/Modules/Resonance2017.py, Plotting/Modules/Resonance2018.py, Plotting/SampleManager.py
[mmumu_nosel_NLOPU.pdf](https://github.com/albertobelloni/WG_Analysis/files/3963443/mmumu_nosel_NLOPU.pdf)
=> add Z to truelep_mother cut, WGPt130 name change

Analysis/TreeFilter/Core/python/core.py, Analysis/TreeFilter/Core/python/scheduler_base.py, Analysis/TreeFilter/FilterOverlap/scripts/Conf.py, Analysis/TreeFilter/FilterOverlap/scripts/scheduler.py, Analysis/TreeFilter/FilterOverlap/src/RunAnalysis.cxx, Analysis/TreeFilter/Makefile.mk, Plotting/MakeBase.py, Plotting/MakeWGPhCutValidPlot.py, Plotting/SampleManager.py
Events in the bottom are FSR with W as mother and are prompt final state particles; those on the left axis contain pair-produced photons, so they are not final state. We need to capture both. Essentially we need to cut on this pT `Max$(trueph_pt*(trueph_status==23||(abs(trueph_motherPID)==24&&trueph_isPromptFS)))`
=> WGamma PtG stitching

Plotting/FitManager.py, Plotting/MakeBase.py, Plotting/MakeEFake.py, Plotting/MakeEFakeValidPlot.py, Plotting/MakeZFit.py, Plotting/SampleManager.py, Plotting/selection_defs.py
- update fit method
- add validation plots for e fake study
- e fake estimation by detector quality bins
- more refactoring with helper functions
=> E fake fitter update

Analysis/TreeFilter/Core/python/scheduler_base.py, Plotting/MatrixUncertaintyTest.py
Output example:
```
[kakw@siab-1 Plotting]$ python MatrixUncertaintyTest.py
epsilon^T_gamma, epsilon^T_J 1.000+/-0.010 0.40+/-0.05
N_T, N_L (1.60+/-0.04)e+03 150+/-10
Matrix:
[[1.  0.4]
[0.  0.6]]
X alpha =  [1600.  150.]
Inverted matrix:
[[ 1.         -0.66666667]
[ 0.          1.66666667]]
1. solved equation with uncertainty package:  100+/-24
2. fully by hand error propagation: 100 +/- 24.0514
3. numpy+uncertainty array implementation:  100+/-24
equivalent sample size: Zgamma 100 Z+jets 95
4. Monte Carlo estimate of 10000 matrices: 101.546 +/- 22.7397
3.66 percent above 2 sigma (2.5% normally), that is, estimates larger than 147.026
0.77 percent below 2 sigma (2.5% normally), that is, estimates smaller than 56.0668
```
=> matrix uncertainty propagation

Plotting/MakeBase.py, Plotting/MakeFits.py, Plotting/cross_sections/photon16_smallsig.py, Plotting/limitplot.py
New options for MakeLimits class
rmin, rmax, seed: scan range for signal strength/ POI, random seed
doImpact: Make impact plots
floatBkg: allow background to float
numberOfToys: number of combine generated toys (-1 for Asimov, 0 for "data")
noShapeUnc: remove shape systematics
=> New Combine Diagnostic Options

Plotting/FitManager.py
Avoids parameter being at limit
=> Increase range for CB cut1_val

Analysis/TreeFilter/RecoResonance/include/RunAnalysis.h, Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx, Plotting/Modules/Resonance2016.py, Plotting/Modules/Resonance2017.py, Plotting/Modules/Resonance2018.py, Plotting/PlotCLRange.py, Plotting/SampleManager.py
RecoResonance:
Includes BranchDefs.h in RunAnalysis.h so the header file is aware of the existence of prefweight branches during variable definition.
SampleManager:
Fixes the bug where it fails to print count total when it is zero.
PlotCLRange.py:
Extracts results from many toy data trials from HiggsCombine and makes histogram.
=> RecoResonance and SampleManager bug fix

Analysis/TreeFilter/Core/src/AnalysisBase.cxx, Analysis/TreeFilter/RecoResonance/include/RoccoR.h, Analysis/TreeFilter/RecoResonance/include/RunAnalysis.h, Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx
Include by-hand MET uncertainty in ntuples for comparison purposes
=> By Hand MET uncertainty variations in ntuples

Plotting/FitManager.py, Plotting/MakeFits.py, Plotting/MakeSignalWS.py
- Fix indexing in `calculate_func_pdf`
- Use `getError()` instead of `getErrorHi()` to avoid large errors when Minos fail
- Pass acceptance instead of count as norm in signal fits for correct normalization
- Change fit range in signal fits
=> Fit normalization and parameter uncertainty bug fix

Plotting/FitManager.py, Plotting/MakeBase.py, Plotting/MakeFits.py, Plotting/MakeMCBkgWS.py, Plotting/MakeSignalWS.py, Plotting/MakeSystematics.py, Plotting/SampleManager.py, Plotting/selection_defs.py
add electron, photon pt scale, add btag scale factor, 
add hard coded Signal Norm correction, 
Use continuous photon pt cut (only one region 'A')
=> add new systematics, Signal Norm correction, 

Plotting/FitManager.py, Plotting/MakeFits.py, Plotting/MakeMCBkgWS.py, Plotting/MakeSystematics.py, Plotting/limitplot.py, Plotting/limitplot_compare2Hadronic.py, Plotting/limitplots.py, Plotting/para_Smodel.py, Plotting/selection_defs.py
do `python para_Smodel.py` to generate `data/sigfit_para` and then use this in `MakeFits.py`
=> add para_Smodel.py to extract parameter functions

Plotting/MakeFits.py, Plotting/Make_unblinded_data.py, Plotting/SampleManager.py, Plotting/limitplot.py, Plotting/para_Smodel.py
add Make_unblinded_data.py to unblind data
=> add script to unblind data 

Plotting/MakeSystematics.py
Missed one file, probably this should both use the same function someday...
=> Use recalculated MET uncertainties in MakeSystematics

Analysis/TreeFilter/RecoResonance/scripts/Conf2016.py, Analysis/TreeFilter/RecoResonance/scripts/Conf2017.py, Analysis/TreeFilter/RecoResonance/scripts/Conf2018.py, Analysis/TreeFilter/RecoResonance/src/RunAnalysis.cxx, Analysis/TreeFilter/Template/scripts/ConfTemplate.py, Plotting/index.php
Check with signal sample
Before:
After:
=> Discard photons in ECAL crack region

Plotting/FitManager.py, Plotting/MakeLatexSampleList.py, Plotting/Make_bkg.py, Plotting/Make_unblinded_data.py, Plotting/SampleManager.py, Plotting/limitplot.py, Plotting/para_Smodel.py, Plotting/selection_defs.py
No major changes, just to synchronize files
=> sync files 

Plotting/MakeFits.py, Plotting/MakeSignalWS.py, Plotting/MakeSystematics.py, Plotting/Make_unblinded_data.py, Plotting/selection_defs.py
Previously the ElectronRes, PhotonRes and UnclusteredEn are missing from the final datacards. Now add them.
=> add complete systematics
